services:
  postgresql:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "35432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/

volumes:
  postgresql: { }

networks:
  backend:
    driver: bridge
