server:
  port: 8083

spring:
  application:
    name: achievepoint
  datasource:
    url: jdbc:postgresql://achievepoint_db:5432/achievepoint_db
    username: achievepoint_user
    password: achievepoint_password
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

management:
  endpoint:
    health:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include:
          - health
  server:
    port: 8083

grpc:
  client:
    authpoint:
      address: static://tochkaszapyatoi.ru:9098
      negotiation-type: plaintext
